package hamid.msv.mikot.util

const val NO_PROFILE_IMAGE = "no_profile_image"
const val NO_BIO = "no_bio"
const val FIREBASE_DATABASE_URL = "https://mikot-6393a-default-rtdb.firebaseio.com/"
const val LAST_MESSAGE_SEND_IMAGE = "sent an image"
const val LAST_MESSAGE_SEND_VIDEO = "sent a video"
const val LAST_MESSAGE_SEND_MUSIC = "sent a music"
const val LAST_MESSAGE_SEND_FILE = "sent a file"
const val LAST_MESSAGE_SEND_LOCATION = "sent a location"
const val GET_ALL_USERS_KEY = "get_all_users"
const val GET_ALL_MESSAGES_KEY = "get_all_messages"
const val GET_LAST_MESSAGES_KEY = "get_last_message"
const val DATABASE_ERROR_KEY = "database_error"
const val PREFERENCES_NAME = "mikot_preferences"
const val ON_BOARDING_PREFERENCES_KEY = "on_boarding_key"