package hamid.msv.mikot.ui.theme

import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

// Padding values
val EXTRA_SMALL_PADDING = 4.dp
val SMALL_PADDING = 8.dp
val MEDIUM_PADDING = 12.dp
val EXTRA_MEDIUM_PADDING = 18.dp
val LARGE_PADDING = 24.dp
val EXTRA_LARGE_PADDING = 48.dp

// Welcome Screen
val PAGER_INDICATOR_WIDTH = 12.dp
val PAGER_INDICATOR_SPACE = 8.dp
val FINISH_BUTTON_HEIGHT = 56.dp
val FINISH_BUTTON_CORNER_RADIUS = 8.dp
val FINISH_BUTTON_ELEVATION = 8.dp

// Register Screen
val REGISTER_TEXT_FIELD_CORNER_RADIUS = 8.dp
val REGISTER_BUTTON_CORNER_RADIUS = 16.dp
val REGISTER_BUTTON_ELEVATION = 4.dp
val REGISTER_BUTTON_HEIGHT = 56.dp

// Home Screen
val HOME_SCREEN_ITEM_HEIGHT = 75.dp
val HOME_SCREEN_ITEM_ELEVATION = 2.dp
val HOME_SCREEN_ITEM_CORNER_RADIUS = 8.dp
val HOME_SCREEN_ITEM_IMAGE_SIZE = 50.dp
val HOME_SCREEN_ITEM_NAME_TEXT_SIZE = 18.sp
val HOME_FAB_SIZE = 56.dp
val HOME_FAB_CORNER_RADIUS = 10.dp
val HOME_TOP_BAR_HEIGHT = 56.dp
val HOME_TOP_BAR_CORNER_RADIUS = 10.dp
val HOME_TOP_BAR_ELEVATION = 6.dp
val HOME_TOP_BAR_TEXT_SIZE = 28.sp

// Chat Screen
val MESSAGE_ITEM_CORNER_RADIUS = 12.dp
val CHAT_TOP_BAR_HEIGHT = 68.dp
val CHAT_TOP_BAR_CORNER_RADIUS = 12.dp
val CHAT_TOP_BAR_ELEVATION = 6.dp
val CHAT_TEXT_FIELD_ELEVATION = 2.dp
val CHAT_TEXT_FIELD_CORNER_RADIUS = 16.dp

// ContactScreen
val CONTACT_SCREEN_ITEM_HEIGHT = 80.dp
val CONTACT_SCREEN_ITEM_ELEVATION = 4.dp
val CONTACT_SCREEN_ITEM_CORNER_RADIUS = 12.dp
val CONTACT_SCREEN_ITEM_IMAGE_SIZE = 55.dp
val CONTACT_SCREEN_ITEM_NAME_TEXT_SIZE = 18.sp